name: Proyecto Python TDD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Instalar dependencias (pytest)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ejecutar tests suma
        run: pytest tests/test_suma.py
      - name: Ejecutar tests resta
        run: pytest tests/test_resta.py
      - name: Ejecutar tests multiplicacion
        run: pytest tests/test_multi.py
      - name: Ejecutar tests div
        run: pytest tests/text_division.py
